### ISSUE TITLE
[1.18.2] Server startup crashes with elementary ores

### ISSUE THREAD

**Issue by BugmanBugman** [Lothrazar/elementary-ores#10]
Minecraft Version: 1.18.2

Mod Version: 1.0.3

Single Player or Server: server

Log file link:

[crash-2022-03-24_17.41.25-fml.txt](https://github.com/Lothrazar/ElementaryOres/files/8346157/crash-2022-03-24_17.41.25-fml.txt)

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3875308
