### ISSUE TITLE
Ghast Ore Does Not Have a Loot Table

### ISSUE THREAD

**Issue by Darkosto** [Lothrazar/elementary-ores#12]
Minecraft Version: 1.18.2

Forge Version: 40.1.60

Mod Version: 1.1.0

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened):
Ghast Ores do not have a loot table

It might worth considering having the ore drop a "ghast tear" chunk and require processing? Or just stick with silk touch to get the ore and cook it in a furnace

**Comment by Lothrazar** [comment]
https://www.curseforge.com/minecraft/mc-mods/elementary-ores/files/3875308
